spring:
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://rc1d-pfsfhzyjbmplu9be.mdb.yandexcloud.net:6432/schedule?targetServerType=master&ssl=false&sslmode=disable
    username: schedule
    password: schedule
    driver-class-name: org.postgresql.Driver

logging:
  level:
    web: debug

public:
  key:
    filename: "/public_key.der"
